// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/validator/accounts/v2/web_api.proto

package ethereum_validator_accounts_v2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateWalletRequest_KeymanagerKind int32

const (
	CreateWalletRequest_DERIVED CreateWalletRequest_KeymanagerKind = 0
	CreateWalletRequest_DIRECT  CreateWalletRequest_KeymanagerKind = 1
	CreateWalletRequest_REMOTE  CreateWalletRequest_KeymanagerKind = 2
)

var CreateWalletRequest_KeymanagerKind_name = map[int32]string{
	0: "DERIVED",
	1: "DIRECT",
	2: "REMOTE",
}

var CreateWalletRequest_KeymanagerKind_value = map[string]int32{
	"DERIVED": 0,
	"DIRECT":  1,
	"REMOTE":  2,
}

func (x CreateWalletRequest_KeymanagerKind) String() string {
	return proto.EnumName(CreateWalletRequest_KeymanagerKind_name, int32(x))
}

func (CreateWalletRequest_KeymanagerKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{0, 0}
}

type ListStatusesResponse_ValidatorStatus int32

const (
	ListStatusesResponse_UNKNOWN_STATUS ListStatusesResponse_ValidatorStatus = 0
	ListStatusesResponse_DEPOSITED      ListStatusesResponse_ValidatorStatus = 1
	ListStatusesResponse_PENDING        ListStatusesResponse_ValidatorStatus = 2
	ListStatusesResponse_ACTIVE         ListStatusesResponse_ValidatorStatus = 3
	ListStatusesResponse_EXITING        ListStatusesResponse_ValidatorStatus = 4
	ListStatusesResponse_SLASHING       ListStatusesResponse_ValidatorStatus = 5
	ListStatusesResponse_EXITED         ListStatusesResponse_ValidatorStatus = 6
	ListStatusesResponse_INVALID        ListStatusesResponse_ValidatorStatus = 7
)

var ListStatusesResponse_ValidatorStatus_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "DEPOSITED",
	2: "PENDING",
	3: "ACTIVE",
	4: "EXITING",
	5: "SLASHING",
	6: "EXITED",
	7: "INVALID",
}

var ListStatusesResponse_ValidatorStatus_value = map[string]int32{
	"UNKNOWN_STATUS": 0,
	"DEPOSITED":      1,
	"PENDING":        2,
	"ACTIVE":         3,
	"EXITING":        4,
	"SLASHING":       5,
	"EXITED":         6,
	"INVALID":        7,
}

func (x ListStatusesResponse_ValidatorStatus) String() string {
	return proto.EnumName(ListStatusesResponse_ValidatorStatus_name, int32(x))
}

func (ListStatusesResponse_ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{9, 0}
}

type CreateWalletRequest struct {
	WalletPath           string                             `protobuf:"bytes,1,opt,name=wallet_path,json=walletPath,proto3" json:"wallet_path,omitempty"`
	Keymanager           CreateWalletRequest_KeymanagerKind `protobuf:"varint,2,opt,name=keymanager,proto3,enum=ethereum.validator.accounts.v2.CreateWalletRequest_KeymanagerKind" json:"keymanager,omitempty"`
	WalletPassword       string                             `protobuf:"bytes,3,opt,name=wallet_password,json=walletPassword,proto3" json:"wallet_password,omitempty"`
	Mnemonic             string                             `protobuf:"bytes,4,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	NumAccounts          uint64                             `protobuf:"varint,5,opt,name=num_accounts,json=numAccounts,proto3" json:"num_accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *CreateWalletRequest) Reset()         { *m = CreateWalletRequest{} }
func (m *CreateWalletRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWalletRequest) ProtoMessage()    {}
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{0}
}

func (m *CreateWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletRequest.Unmarshal(m, b)
}
func (m *CreateWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletRequest.Marshal(b, m, deterministic)
}
func (m *CreateWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletRequest.Merge(m, src)
}
func (m *CreateWalletRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWalletRequest.Size(m)
}
func (m *CreateWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletRequest proto.InternalMessageInfo

func (m *CreateWalletRequest) GetWalletPath() string {
	if m != nil {
		return m.WalletPath
	}
	return ""
}

func (m *CreateWalletRequest) GetKeymanager() CreateWalletRequest_KeymanagerKind {
	if m != nil {
		return m.Keymanager
	}
	return CreateWalletRequest_DERIVED
}

func (m *CreateWalletRequest) GetWalletPassword() string {
	if m != nil {
		return m.WalletPassword
	}
	return ""
}

func (m *CreateWalletRequest) GetMnemonic() string {
	if m != nil {
		return m.Mnemonic
	}
	return ""
}

func (m *CreateWalletRequest) GetNumAccounts() uint64 {
	if m != nil {
		return m.NumAccounts
	}
	return 0
}

type EditWalletConfigRequest struct {
	RemoteAddr           string   `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	RemoteCrtPath        string   `protobuf:"bytes,2,opt,name=remote_crt_path,json=remoteCrtPath,proto3" json:"remote_crt_path,omitempty"`
	RemoteKeyPath        string   `protobuf:"bytes,3,opt,name=remote_key_path,json=remoteKeyPath,proto3" json:"remote_key_path,omitempty"`
	RemoteCaCrtPath      string   `protobuf:"bytes,4,opt,name=remote_ca_crt_path,json=remoteCaCrtPath,proto3" json:"remote_ca_crt_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditWalletConfigRequest) Reset()         { *m = EditWalletConfigRequest{} }
func (m *EditWalletConfigRequest) String() string { return proto.CompactTextString(m) }
func (*EditWalletConfigRequest) ProtoMessage()    {}
func (*EditWalletConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{1}
}

func (m *EditWalletConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditWalletConfigRequest.Unmarshal(m, b)
}
func (m *EditWalletConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditWalletConfigRequest.Marshal(b, m, deterministic)
}
func (m *EditWalletConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditWalletConfigRequest.Merge(m, src)
}
func (m *EditWalletConfigRequest) XXX_Size() int {
	return xxx_messageInfo_EditWalletConfigRequest.Size(m)
}
func (m *EditWalletConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditWalletConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditWalletConfigRequest proto.InternalMessageInfo

func (m *EditWalletConfigRequest) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *EditWalletConfigRequest) GetRemoteCrtPath() string {
	if m != nil {
		return m.RemoteCrtPath
	}
	return ""
}

func (m *EditWalletConfigRequest) GetRemoteKeyPath() string {
	if m != nil {
		return m.RemoteKeyPath
	}
	return ""
}

func (m *EditWalletConfigRequest) GetRemoteCaCrtPath() string {
	if m != nil {
		return m.RemoteCaCrtPath
	}
	return ""
}

type WalletResponse struct {
	WalletPath           string                           `protobuf:"bytes,1,opt,name=wallet_path,json=walletPath,proto3" json:"wallet_path,omitempty"`
	KeymanagerConfig     *WalletResponse_KeymanagerConfig `protobuf:"bytes,2,opt,name=keymanager_config,json=keymanagerConfig,proto3" json:"keymanager_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *WalletResponse) Reset()         { *m = WalletResponse{} }
func (m *WalletResponse) String() string { return proto.CompactTextString(m) }
func (*WalletResponse) ProtoMessage()    {}
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{2}
}

func (m *WalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletResponse.Unmarshal(m, b)
}
func (m *WalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletResponse.Marshal(b, m, deterministic)
}
func (m *WalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletResponse.Merge(m, src)
}
func (m *WalletResponse) XXX_Size() int {
	return xxx_messageInfo_WalletResponse.Size(m)
}
func (m *WalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WalletResponse proto.InternalMessageInfo

func (m *WalletResponse) GetWalletPath() string {
	if m != nil {
		return m.WalletPath
	}
	return ""
}

func (m *WalletResponse) GetKeymanagerConfig() *WalletResponse_KeymanagerConfig {
	if m != nil {
		return m.KeymanagerConfig
	}
	return nil
}

type WalletResponse_KeymanagerConfig struct {
	Configs              map[string]string `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WalletResponse_KeymanagerConfig) Reset()         { *m = WalletResponse_KeymanagerConfig{} }
func (m *WalletResponse_KeymanagerConfig) String() string { return proto.CompactTextString(m) }
func (*WalletResponse_KeymanagerConfig) ProtoMessage()    {}
func (*WalletResponse_KeymanagerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{2, 0}
}

func (m *WalletResponse_KeymanagerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletResponse_KeymanagerConfig.Unmarshal(m, b)
}
func (m *WalletResponse_KeymanagerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletResponse_KeymanagerConfig.Marshal(b, m, deterministic)
}
func (m *WalletResponse_KeymanagerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletResponse_KeymanagerConfig.Merge(m, src)
}
func (m *WalletResponse_KeymanagerConfig) XXX_Size() int {
	return xxx_messageInfo_WalletResponse_KeymanagerConfig.Size(m)
}
func (m *WalletResponse_KeymanagerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletResponse_KeymanagerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WalletResponse_KeymanagerConfig proto.InternalMessageInfo

func (m *WalletResponse_KeymanagerConfig) GetConfigs() map[string]string {
	if m != nil {
		return m.Configs
	}
	return nil
}

type CreateAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{3}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ListAccountsRequest struct {
	GetDepositTxData     bool     `protobuf:"varint,1,opt,name=get_deposit_tx_data,json=getDepositTxData,proto3" json:"get_deposit_tx_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{4}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetGetDepositTxData() bool {
	if m != nil {
		return m.GetDepositTxData
	}
	return false
}

type ListAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{5}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Account struct {
	ValidatingPublicKey  []byte   `protobuf:"bytes,1,opt,name=validating_public_key,json=validatingPublicKey,proto3" json:"validating_public_key,omitempty"`
	AccountName          string   `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	DepositTxData        []byte   `protobuf:"bytes,3,opt,name=deposit_tx_data,json=depositTxData,proto3" json:"deposit_tx_data,omitempty"`
	DerivationPath       string   `protobuf:"bytes,4,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{6}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetValidatingPublicKey() []byte {
	if m != nil {
		return m.ValidatingPublicKey
	}
	return nil
}

func (m *Account) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *Account) GetDepositTxData() []byte {
	if m != nil {
		return m.DepositTxData
	}
	return nil
}

func (m *Account) GetDerivationPath() string {
	if m != nil {
		return m.DerivationPath
	}
	return ""
}

type AccountRequest struct {
	PublicKeys           [][]byte `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	Indices              []uint64 `protobuf:"varint,2,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{7}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetPublicKeys() [][]byte {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *AccountRequest) GetIndices() []uint64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

type ListBalancesResponse struct {
	PublicKeys           [][]byte `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	Indices              []uint64 `protobuf:"varint,2,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Balances             []uint64 `protobuf:"varint,3,rep,packed,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBalancesResponse) Reset()         { *m = ListBalancesResponse{} }
func (m *ListBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*ListBalancesResponse) ProtoMessage()    {}
func (*ListBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{8}
}

func (m *ListBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBalancesResponse.Unmarshal(m, b)
}
func (m *ListBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBalancesResponse.Marshal(b, m, deterministic)
}
func (m *ListBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBalancesResponse.Merge(m, src)
}
func (m *ListBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_ListBalancesResponse.Size(m)
}
func (m *ListBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBalancesResponse proto.InternalMessageInfo

func (m *ListBalancesResponse) GetPublicKeys() [][]byte {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *ListBalancesResponse) GetIndices() []uint64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *ListBalancesResponse) GetBalances() []uint64 {
	if m != nil {
		return m.Balances
	}
	return nil
}

type ListStatusesResponse struct {
	PublicKeys           [][]byte                               `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	Indices              []uint64                               `protobuf:"varint,2,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Statuses             []ListStatusesResponse_ValidatorStatus `protobuf:"varint,3,rep,packed,name=statuses,proto3,enum=ethereum.validator.accounts.v2.ListStatusesResponse_ValidatorStatus" json:"statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ListStatusesResponse) Reset()         { *m = ListStatusesResponse{} }
func (m *ListStatusesResponse) String() string { return proto.CompactTextString(m) }
func (*ListStatusesResponse) ProtoMessage()    {}
func (*ListStatusesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{9}
}

func (m *ListStatusesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStatusesResponse.Unmarshal(m, b)
}
func (m *ListStatusesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStatusesResponse.Marshal(b, m, deterministic)
}
func (m *ListStatusesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStatusesResponse.Merge(m, src)
}
func (m *ListStatusesResponse) XXX_Size() int {
	return xxx_messageInfo_ListStatusesResponse.Size(m)
}
func (m *ListStatusesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStatusesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStatusesResponse proto.InternalMessageInfo

func (m *ListStatusesResponse) GetPublicKeys() [][]byte {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *ListStatusesResponse) GetIndices() []uint64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *ListStatusesResponse) GetStatuses() []ListStatusesResponse_ValidatorStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type ListPerformanceResponse struct {
	PublicKeys           [][]byte                              `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	Indices              []uint64                              `protobuf:"varint,2,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Submissions          []*ListPerformanceResponse_Submission `protobuf:"bytes,3,rep,name=submissions,proto3" json:"submissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ListPerformanceResponse) Reset()         { *m = ListPerformanceResponse{} }
func (m *ListPerformanceResponse) String() string { return proto.CompactTextString(m) }
func (*ListPerformanceResponse) ProtoMessage()    {}
func (*ListPerformanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{10}
}

func (m *ListPerformanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPerformanceResponse.Unmarshal(m, b)
}
func (m *ListPerformanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPerformanceResponse.Marshal(b, m, deterministic)
}
func (m *ListPerformanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPerformanceResponse.Merge(m, src)
}
func (m *ListPerformanceResponse) XXX_Size() int {
	return xxx_messageInfo_ListPerformanceResponse.Size(m)
}
func (m *ListPerformanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPerformanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPerformanceResponse proto.InternalMessageInfo

func (m *ListPerformanceResponse) GetPublicKeys() [][]byte {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *ListPerformanceResponse) GetIndices() []uint64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *ListPerformanceResponse) GetSubmissions() []*ListPerformanceResponse_Submission {
	if m != nil {
		return m.Submissions
	}
	return nil
}

type ListPerformanceResponse_Submission struct {
	BlockCount           uint64   `protobuf:"varint,1,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	AttestationCount     uint64   `protobuf:"varint,2,opt,name=attestation_count,json=attestationCount,proto3" json:"attestation_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPerformanceResponse_Submission) Reset()         { *m = ListPerformanceResponse_Submission{} }
func (m *ListPerformanceResponse_Submission) String() string { return proto.CompactTextString(m) }
func (*ListPerformanceResponse_Submission) ProtoMessage()    {}
func (*ListPerformanceResponse_Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{10, 0}
}

func (m *ListPerformanceResponse_Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPerformanceResponse_Submission.Unmarshal(m, b)
}
func (m *ListPerformanceResponse_Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPerformanceResponse_Submission.Marshal(b, m, deterministic)
}
func (m *ListPerformanceResponse_Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPerformanceResponse_Submission.Merge(m, src)
}
func (m *ListPerformanceResponse_Submission) XXX_Size() int {
	return xxx_messageInfo_ListPerformanceResponse_Submission.Size(m)
}
func (m *ListPerformanceResponse_Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPerformanceResponse_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_ListPerformanceResponse_Submission proto.InternalMessageInfo

func (m *ListPerformanceResponse_Submission) GetBlockCount() uint64 {
	if m != nil {
		return m.BlockCount
	}
	return 0
}

func (m *ListPerformanceResponse_Submission) GetAttestationCount() uint64 {
	if m != nil {
		return m.AttestationCount
	}
	return 0
}

type AuthRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{11}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenExpiration      uint64   `protobuf:"varint,2,opt,name=token_expiration,json=tokenExpiration,proto3" json:"token_expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{12}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetTokenExpiration() uint64 {
	if m != nil {
		return m.TokenExpiration
	}
	return 0
}

type GenerateMnemonicResponse struct {
	Mnemonic             string   `protobuf:"bytes,1,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateMnemonicResponse) Reset()         { *m = GenerateMnemonicResponse{} }
func (m *GenerateMnemonicResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateMnemonicResponse) ProtoMessage()    {}
func (*GenerateMnemonicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a5153635bfe042e, []int{13}
}

func (m *GenerateMnemonicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateMnemonicResponse.Unmarshal(m, b)
}
func (m *GenerateMnemonicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateMnemonicResponse.Marshal(b, m, deterministic)
}
func (m *GenerateMnemonicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateMnemonicResponse.Merge(m, src)
}
func (m *GenerateMnemonicResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateMnemonicResponse.Size(m)
}
func (m *GenerateMnemonicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateMnemonicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateMnemonicResponse proto.InternalMessageInfo

func (m *GenerateMnemonicResponse) GetMnemonic() string {
	if m != nil {
		return m.Mnemonic
	}
	return ""
}

func init() {
	proto.RegisterEnum("ethereum.validator.accounts.v2.CreateWalletRequest_KeymanagerKind", CreateWalletRequest_KeymanagerKind_name, CreateWalletRequest_KeymanagerKind_value)
	proto.RegisterEnum("ethereum.validator.accounts.v2.ListStatusesResponse_ValidatorStatus", ListStatusesResponse_ValidatorStatus_name, ListStatusesResponse_ValidatorStatus_value)
	proto.RegisterType((*CreateWalletRequest)(nil), "ethereum.validator.accounts.v2.CreateWalletRequest")
	proto.RegisterType((*EditWalletConfigRequest)(nil), "ethereum.validator.accounts.v2.EditWalletConfigRequest")
	proto.RegisterType((*WalletResponse)(nil), "ethereum.validator.accounts.v2.WalletResponse")
	proto.RegisterType((*WalletResponse_KeymanagerConfig)(nil), "ethereum.validator.accounts.v2.WalletResponse.KeymanagerConfig")
	proto.RegisterMapType((map[string]string)(nil), "ethereum.validator.accounts.v2.WalletResponse.KeymanagerConfig.ConfigsEntry")
	proto.RegisterType((*CreateAccountResponse)(nil), "ethereum.validator.accounts.v2.CreateAccountResponse")
	proto.RegisterType((*ListAccountsRequest)(nil), "ethereum.validator.accounts.v2.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "ethereum.validator.accounts.v2.ListAccountsResponse")
	proto.RegisterType((*Account)(nil), "ethereum.validator.accounts.v2.Account")
	proto.RegisterType((*AccountRequest)(nil), "ethereum.validator.accounts.v2.AccountRequest")
	proto.RegisterType((*ListBalancesResponse)(nil), "ethereum.validator.accounts.v2.ListBalancesResponse")
	proto.RegisterType((*ListStatusesResponse)(nil), "ethereum.validator.accounts.v2.ListStatusesResponse")
	proto.RegisterType((*ListPerformanceResponse)(nil), "ethereum.validator.accounts.v2.ListPerformanceResponse")
	proto.RegisterType((*ListPerformanceResponse_Submission)(nil), "ethereum.validator.accounts.v2.ListPerformanceResponse.Submission")
	proto.RegisterType((*AuthRequest)(nil), "ethereum.validator.accounts.v2.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "ethereum.validator.accounts.v2.AuthResponse")
	proto.RegisterType((*GenerateMnemonicResponse)(nil), "ethereum.validator.accounts.v2.GenerateMnemonicResponse")
}

func init() {
	proto.RegisterFile("proto/validator/accounts/v2/web_api.proto", fileDescriptor_8a5153635bfe042e)
}

var fileDescriptor_8a5153635bfe042e = []byte{
	// 1349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x97, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x40, 0x43, 0x4a, 0xb6, 0x95, 0x91, 0x2c, 0x33, 0x6b, 0x27, 0x51, 0x95, 0x34, 0x51, 0x08,
	0x34, 0x71, 0xe2, 0x96, 0x02, 0x94, 0xa6, 0x09, 0x7c, 0x29, 0x14, 0x89, 0x48, 0x04, 0x3b, 0xb2,
	0x41, 0x29, 0x4e, 0x91, 0x1e, 0xd8, 0x95, 0xb8, 0x96, 0x09, 0x8b, 0xa4, 0x4a, 0xae, 0x9c, 0xe8,
	0xd8, 0xa0, 0x87, 0x5e, 0x7a, 0x69, 0x8b, 0x02, 0x45, 0x81, 0x1e, 0xfa, 0x07, 0xb9, 0x34, 0xe8,
	0x67, 0x14, 0x3d, 0xb4, 0x1f, 0xd0, 0x0f, 0x29, 0xb8, 0xbb, 0xa4, 0x28, 0xc1, 0xaa, 0x6c, 0x37,
	0x39, 0x59, 0x3b, 0x33, 0x3b, 0xf3, 0x38, 0xbb, 0xb3, 0x33, 0x86, 0xdb, 0x03, 0xdf, 0xa3, 0x5e,
	0xf9, 0x08, 0xf7, 0x6d, 0x0b, 0x53, 0xcf, 0x2f, 0xe3, 0x6e, 0xd7, 0x1b, 0xba, 0x34, 0x28, 0x1f,
	0x55, 0xca, 0x2f, 0x48, 0xc7, 0xc4, 0x03, 0x5b, 0x63, 0x36, 0xe8, 0x1a, 0xa1, 0x07, 0xc4, 0x27,
	0x43, 0x47, 0x8b, 0xad, 0xb5, 0xc8, 0x5a, 0x3b, 0xaa, 0x14, 0xaf, 0xf6, 0x3c, 0xaf, 0xd7, 0x27,
	0x65, 0x3c, 0xb0, 0xcb, 0xd8, 0x75, 0x3d, 0x8a, 0xa9, 0xed, 0xb9, 0x01, 0xdf, 0x5d, 0xbc, 0x22,
	0xb4, 0x6c, 0xd5, 0x19, 0xee, 0x97, 0x89, 0x33, 0xa0, 0x23, 0xae, 0x54, 0x7f, 0x97, 0x61, 0xb5,
	0xe6, 0x13, 0x4c, 0xc9, 0x33, 0xdc, 0xef, 0x13, 0x6a, 0x90, 0x2f, 0x87, 0x24, 0xa0, 0xe8, 0x3a,
	0x64, 0x5f, 0x30, 0x81, 0x39, 0xc0, 0xf4, 0xa0, 0x20, 0x95, 0xa4, 0xf5, 0xf3, 0x06, 0x70, 0xd1,
	0x2e, 0xa6, 0x07, 0xa8, 0x03, 0x70, 0x48, 0x46, 0x0e, 0x76, 0x71, 0x8f, 0xf8, 0x05, 0xb9, 0x24,
	0xad, 0xe7, 0x2b, 0x0f, 0xb5, 0xff, 0x06, 0xd5, 0x8e, 0x89, 0xa4, 0x6d, 0xc5, 0x5e, 0xb6, 0x6c,
	0xd7, 0x32, 0x12, 0x5e, 0xd1, 0x2d, 0x58, 0x89, 0x21, 0x82, 0xe0, 0x85, 0xe7, 0x5b, 0x85, 0x14,
	0x03, 0xc9, 0x47, 0x20, 0x5c, 0x8a, 0x8a, 0x90, 0x71, 0x5c, 0xe2, 0x78, 0xae, 0xdd, 0x2d, 0xa4,
	0x99, 0x45, 0xbc, 0x46, 0x37, 0x20, 0xe7, 0x0e, 0x1d, 0x33, 0xc2, 0x28, 0x2c, 0x94, 0xa4, 0xf5,
	0xb4, 0x91, 0x75, 0x87, 0x4e, 0x55, 0x88, 0xd4, 0x7b, 0x90, 0x9f, 0xa4, 0x40, 0x59, 0x58, 0xaa,
	0xeb, 0x46, 0x63, 0x4f, 0xaf, 0x2b, 0xe7, 0x10, 0xc0, 0x62, 0xbd, 0x61, 0xe8, 0xb5, 0xb6, 0x22,
	0x85, 0xbf, 0x0d, 0xfd, 0xc9, 0x4e, 0x5b, 0x57, 0x64, 0xf5, 0x8d, 0x04, 0x97, 0x75, 0xcb, 0xa6,
	0xfc, 0x7b, 0x6a, 0x9e, 0xbb, 0x6f, 0xf7, 0x12, 0xf9, 0xf3, 0x89, 0xe3, 0x51, 0x62, 0x62, 0xcb,
	0xf2, 0xa3, 0xfc, 0x71, 0x51, 0xd5, 0xb2, 0x7c, 0x74, 0x13, 0x56, 0x84, 0x41, 0xd7, 0x17, 0x49,
	0x96, 0x99, 0xd1, 0x32, 0x17, 0xd7, 0x7c, 0x9e, 0xe7, 0xb1, 0xdd, 0x21, 0x19, 0x71, 0xbb, 0x54,
	0xd2, 0x6e, 0x8b, 0x8c, 0x98, 0xdd, 0x06, 0xa0, 0xc8, 0x1f, 0x1e, 0xbb, 0xe4, 0xc9, 0x10, 0x1e,
	0x6a, 0x58, 0x38, 0x55, 0xff, 0x96, 0x21, 0x1f, 0x9d, 0x42, 0x30, 0xf0, 0xdc, 0x80, 0xcc, 0x3f,
	0xf0, 0x3e, 0x5c, 0x18, 0x1f, 0x8d, 0xd9, 0x65, 0x5f, 0xcb, 0x90, 0xb3, 0x95, 0x4f, 0xe7, 0x9d,
	0xfb, 0x64, 0xac, 0xc4, 0x91, 0x8b, 0xa4, 0x29, 0x87, 0x53, 0x92, 0xe2, 0x6f, 0x12, 0x28, 0xd3,
	0x66, 0x68, 0x1f, 0x96, 0x78, 0xdc, 0xa0, 0x20, 0x95, 0x52, 0xeb, 0xd9, 0xca, 0xf6, 0xff, 0x0c,
	0xac, 0xf1, 0x3f, 0x81, 0xee, 0x52, 0x7f, 0x64, 0x44, 0xce, 0x8b, 0x9b, 0x90, 0x4b, 0x2a, 0x90,
	0x02, 0xa9, 0x43, 0x32, 0x12, 0x39, 0x09, 0x7f, 0xa2, 0x35, 0x58, 0x38, 0xc2, 0xfd, 0x21, 0x11,
	0x67, 0xc6, 0x17, 0x9b, 0xf2, 0x03, 0x49, 0x7d, 0x0e, 0x17, 0xf9, 0x2d, 0x17, 0xb7, 0x2b, 0x4e,
	0x70, 0x15, 0x96, 0x04, 0x19, 0x73, 0x94, 0xad, 0xdc, 0x9a, 0x07, 0x1f, 0x79, 0x88, 0xf6, 0xa9,
	0x75, 0x58, 0xdd, 0xb6, 0x03, 0x1a, 0xdd, 0xdb, 0xe8, 0xae, 0x7d, 0x04, 0xab, 0x3d, 0x42, 0x4d,
	0x8b, 0x0c, 0xbc, 0xc0, 0xa6, 0x26, 0x7d, 0x69, 0x5a, 0x98, 0x62, 0x16, 0x25, 0x63, 0x28, 0x3d,
	0x42, 0xeb, 0x5c, 0xd3, 0x7e, 0x59, 0xc7, 0x14, 0xab, 0x9f, 0xc3, 0xda, 0xa4, 0x17, 0x01, 0x58,
	0x83, 0x4c, 0x5c, 0x24, 0x3c, 0xbd, 0x27, 0x26, 0x8c, 0x37, 0xaa, 0xaf, 0x25, 0x58, 0x12, 0x52,
	0x54, 0x81, 0x8b, 0x62, 0x9b, 0xed, 0xf6, 0xcc, 0xc1, 0xb0, 0xd3, 0xb7, 0xbb, 0x66, 0x94, 0xc8,
	0x9c, 0xb1, 0x3a, 0x56, 0xee, 0x32, 0xdd, 0x16, 0x19, 0x85, 0xd5, 0x2a, 0x7c, 0x99, 0x2e, 0x76,
	0xa2, 0xfc, 0x66, 0x85, 0xac, 0x89, 0x1d, 0x12, 0x56, 0xc4, 0xf4, 0xa7, 0xa6, 0x98, 0xc3, 0x65,
	0x2b, 0xf9, 0x9d, 0xe1, 0xeb, 0x61, 0x11, 0xdf, 0x3e, 0x62, 0x8f, 0x61, 0xb2, 0x1c, 0xf2, 0x63,
	0x31, 0xab, 0x86, 0x2d, 0xc8, 0xc7, 0x87, 0x15, 0x57, 0xef, 0x18, 0x97, 0x67, 0x23, 0x67, 0xc0,
	0x20, 0xa2, 0x0c, 0x50, 0x01, 0x96, 0x6c, 0xd7, 0xb2, 0xbb, 0x24, 0x28, 0xc8, 0xa5, 0xd4, 0x7a,
	0xda, 0x88, 0x96, 0xaa, 0xc3, 0xb3, 0xfb, 0x10, 0xf7, 0xb1, 0xdb, 0x25, 0x41, 0xb2, 0xbe, 0xce,
	0xe8, 0x32, 0x7c, 0xdd, 0x3a, 0xc2, 0x5d, 0x21, 0xc5, 0x54, 0xf1, 0x5a, 0x7d, 0x23, 0xf3, 0x78,
	0x2d, 0x8a, 0xe9, 0x30, 0x78, 0x3b, 0xf1, 0xbe, 0x80, 0x4c, 0x20, 0xdc, 0xb1, 0x78, 0xf9, 0x4a,
	0x7d, 0xde, 0x45, 0x38, 0x0e, 0x41, 0xdb, 0x8b, 0x4c, 0xb9, 0xc6, 0x88, 0xbd, 0xaa, 0x5f, 0x49,
	0xb0, 0x32, 0xa5, 0x45, 0x08, 0xf2, 0x4f, 0x9b, 0x5b, 0xcd, 0x9d, 0x67, 0x4d, 0xb3, 0xd5, 0xae,
	0xb6, 0x9f, 0xb6, 0x94, 0x73, 0x68, 0x19, 0xce, 0xd7, 0xf5, 0xdd, 0x9d, 0x56, 0xa3, 0xad, 0xd7,
	0x15, 0x29, 0x7c, 0x95, 0x77, 0xf5, 0x66, 0xbd, 0xd1, 0x7c, 0xa4, 0xc8, 0xe1, 0x4b, 0x5c, 0xad,
	0xb5, 0x1b, 0x7b, 0xba, 0x92, 0x0a, 0x15, 0xfa, 0x67, 0x8d, 0x76, 0xa8, 0x48, 0xa3, 0x1c, 0x64,
	0x5a, 0xdb, 0xd5, 0xd6, 0xe3, 0x70, 0xb5, 0x10, 0x9a, 0x85, 0x2a, 0xbd, 0xae, 0x2c, 0x86, 0x66,
	0x8d, 0xe6, 0x5e, 0x75, 0xbb, 0x51, 0x57, 0x96, 0xd4, 0x1f, 0x65, 0xb8, 0x1c, 0x62, 0xef, 0x12,
	0x7f, 0xdf, 0xf3, 0x9d, 0x30, 0x9d, 0x6f, 0x23, 0x79, 0x16, 0x64, 0x83, 0x61, 0xc7, 0xb1, 0x83,
	0x20, 0x6c, 0xc1, 0x2c, 0x7f, 0xd9, 0xf9, 0x8d, 0x71, 0x06, 0x88, 0xd6, 0x8a, 0x5d, 0x19, 0x49,
	0xb7, 0xc5, 0xe7, 0x00, 0x63, 0x55, 0x88, 0xdb, 0xe9, 0x7b, 0xdd, 0x43, 0x73, 0xfc, 0xbc, 0xa4,
	0x0d, 0x60, 0xa2, 0x1a, 0xab, 0xc4, 0x0d, 0xb8, 0x80, 0x29, 0x25, 0x01, 0x1f, 0x0c, 0x84, 0x99,
	0xcc, 0xcc, 0x94, 0x84, 0x82, 0x19, 0xab, 0xb7, 0x21, 0x5b, 0x1d, 0xd2, 0x83, 0xa8, 0x16, 0x8a,
	0x90, 0x89, 0xbb, 0x2f, 0x7f, 0x01, 0xe3, 0xb5, 0xba, 0x03, 0x39, 0x6e, 0x2a, 0xf2, 0xb6, 0x06,
	0x0b, 0xd4, 0x3b, 0x24, 0xae, 0x30, 0xe4, 0x0b, 0x74, 0x1b, 0x14, 0xf6, 0xc3, 0x24, 0x2f, 0x07,
	0xb6, 0xcf, 0x22, 0x89, 0xe0, 0x2b, 0x4c, 0xae, 0xc7, 0x62, 0xf5, 0x13, 0x28, 0x3c, 0x22, 0x2e,
	0xf1, 0x31, 0x25, 0x4f, 0x44, 0x03, 0x8f, 0x9d, 0x27, 0x9b, 0xbc, 0x34, 0xd9, 0xe4, 0x2b, 0x7f,
	0xa4, 0x61, 0x91, 0xbf, 0xf5, 0xe8, 0x67, 0x09, 0x72, 0xc9, 0x39, 0x03, 0xdd, 0x3d, 0xc3, 0x54,
	0x52, 0xd4, 0x4e, 0xd7, 0x59, 0xd4, 0x9b, 0xaf, 0xfe, 0xfc, 0xe7, 0x7b, 0xb9, 0xa4, 0x5e, 0x09,
	0xa7, 0xb7, 0xf1, 0x4c, 0xc7, 0xfb, 0x67, 0xb9, 0xcb, 0x22, 0x6c, 0x4a, 0x77, 0xd0, 0xaf, 0x12,
	0x40, 0x38, 0x33, 0x88, 0x8e, 0x76, 0x7f, 0x5e, 0x98, 0x19, 0xf3, 0xc5, 0xa9, 0xf9, 0x36, 0x18,
	0xdf, 0x07, 0x6a, 0xe9, 0x78, 0x3e, 0xe6, 0xbb, 0x4c, 0x2c, 0x9b, 0x86, 0x90, 0x14, 0x72, 0xc9,
	0x98, 0xe8, 0x92, 0xc6, 0x47, 0x48, 0x2d, 0x1a, 0x21, 0x35, 0x3d, 0x1c, 0x21, 0x4f, 0x0d, 0x71,
	0x95, 0x41, 0x5c, 0x42, 0x6b, 0xc7, 0x41, 0xa0, 0x6f, 0x25, 0x50, 0xa6, 0x0f, 0x7f, 0x66, 0xe8,
	0x07, 0xf3, 0x42, 0xcf, 0xba, 0x46, 0xea, 0x2d, 0x06, 0x71, 0x03, 0x5d, 0x9f, 0x84, 0x88, 0xae,
	0x52, 0xb9, 0x27, 0x36, 0x56, 0x5e, 0xcb, 0x90, 0x89, 0x9a, 0x24, 0xfa, 0x46, 0x82, 0xe5, 0x89,
	0xbe, 0x3e, 0x93, 0xec, 0xde, 0xc9, 0xae, 0xdb, 0xd4, 0x78, 0xa0, 0xae, 0x33, 0x2c, 0x55, 0x7d,
	0x7f, 0x12, 0x2b, 0xfe, 0xa7, 0x60, 0x7c, 0x85, 0x7e, 0x92, 0x20, 0x97, 0x6c, 0xe0, 0xf3, 0x2f,
	0xf8, 0x31, 0x43, 0x43, 0xf1, 0xe3, 0xd3, 0x6d, 0x12, 0x94, 0xd7, 0x18, 0x65, 0x01, 0x5d, 0x3a,
	0x9e, 0xb2, 0xf2, 0x57, 0x0a, 0x16, 0x1f, 0x13, 0xdc, 0xa7, 0x07, 0xe8, 0x07, 0x81, 0x19, 0x75,
	0x42, 0xa4, 0x9d, 0x74, 0x9a, 0x38, 0x0d, 0xe1, 0x74, 0x9f, 0x9d, 0x45, 0x18, 0x35, 0xcc, 0x18,
	0x2b, 0xea, 0x56, 0xef, 0x06, 0x6b, 0xba, 0x17, 0xce, 0xc2, 0x8a, 0x3a, 0x22, 0xfa, 0x45, 0x82,
	0x95, 0xa9, 0x26, 0x70, 0x6a, 0xb2, 0xfb, 0x67, 0xec, 0x32, 0xaa, 0xca, 0xe0, 0xae, 0xa2, 0xe2,
	0x24, 0xdc, 0x60, 0x6c, 0x1a, 0x54, 0xbe, 0x93, 0x21, 0x1d, 0xbe, 0xf5, 0xe8, 0x95, 0x04, 0x0b,
	0xdb, 0x5e, 0xcf, 0x76, 0xd1, 0xc6, 0x5c, 0xbe, 0x71, 0x1b, 0x29, 0x7e, 0x78, 0x32, 0xe3, 0xc9,
	0x74, 0xa9, 0xab, 0x93, 0x44, 0xfd, 0x30, 0x6e, 0x58, 0x03, 0x5f, 0x4b, 0xb0, 0xd8, 0xb2, 0x7b,
	0xee, 0x70, 0xf0, 0x2e, 0x29, 0xae, 0x33, 0x8a, 0xf7, 0xd4, 0xa9, 0xf7, 0x2a, 0x60, 0x81, 0x37,
	0xa5, 0x3b, 0x9d, 0x45, 0x56, 0xfb, 0x77, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xde, 0x31,
	0x9f, 0xcc, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	EditConfig(ctx context.Context, in *EditWalletConfigRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	WalletConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*WalletResponse, error)
	GenerateMnemonic(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenerateMnemonicResponse, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Wallet/CreateWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) EditConfig(ctx context.Context, in *EditWalletConfigRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Wallet/EditConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) WalletConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*WalletResponse, error) {
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Wallet/WalletConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GenerateMnemonic(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenerateMnemonicResponse, error) {
	out := new(GenerateMnemonicResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Wallet/GenerateMnemonic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	CreateWallet(context.Context, *CreateWalletRequest) (*WalletResponse, error)
	EditConfig(context.Context, *EditWalletConfigRequest) (*WalletResponse, error)
	WalletConfig(context.Context, *empty.Empty) (*WalletResponse, error)
	GenerateMnemonic(context.Context, *empty.Empty) (*GenerateMnemonicResponse, error)
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) CreateWallet(ctx context.Context, req *CreateWalletRequest) (*WalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (*UnimplementedWalletServer) EditConfig(ctx context.Context, req *EditWalletConfigRequest) (*WalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditConfig not implemented")
}
func (*UnimplementedWalletServer) WalletConfig(ctx context.Context, req *empty.Empty) (*WalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletConfig not implemented")
}
func (*UnimplementedWalletServer) GenerateMnemonic(ctx context.Context, req *empty.Empty) (*GenerateMnemonicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMnemonic not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Wallet/CreateWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_EditConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditWalletConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).EditConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Wallet/EditConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).EditConfig(ctx, req.(*EditWalletConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_WalletConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).WalletConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Wallet/WalletConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).WalletConfig(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GenerateMnemonic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GenerateMnemonic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Wallet/GenerateMnemonic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GenerateMnemonic(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ethereum.validator.accounts.v2.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _Wallet_CreateWallet_Handler,
		},
		{
			MethodName: "EditConfig",
			Handler:    _Wallet_EditConfig_Handler,
		},
		{
			MethodName: "WalletConfig",
			Handler:    _Wallet_WalletConfig_Handler,
		},
		{
			MethodName: "GenerateMnemonic",
			Handler:    _Wallet_GenerateMnemonic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/validator/accounts/v2/web_api.proto",
}

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	CreateAccount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
}

type accountsClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsClient(cc grpc.ClientConnInterface) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) CreateAccount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Accounts/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Accounts/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	CreateAccount(context.Context, *empty.Empty) (*CreateAccountResponse, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
}

// UnimplementedAccountsServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsServer struct {
}

func (*UnimplementedAccountsServer) CreateAccount(ctx context.Context, req *empty.Empty) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedAccountsServer) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Accounts/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateAccount(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Accounts/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ethereum.validator.accounts.v2.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _Accounts_CreateAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Accounts_ListAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/validator/accounts/v2/web_api.proto",
}

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthClient interface {
	ListBalances(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*ListBalancesResponse, error)
	ListStatuses(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*ListStatusesResponse, error)
	ListPerformance(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*ListPerformanceResponse, error)
}

type healthClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthClient(cc grpc.ClientConnInterface) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) ListBalances(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*ListBalancesResponse, error) {
	out := new(ListBalancesResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Health/ListBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) ListStatuses(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*ListStatusesResponse, error) {
	out := new(ListStatusesResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Health/ListStatuses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) ListPerformance(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*ListPerformanceResponse, error) {
	out := new(ListPerformanceResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Health/ListPerformance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
type HealthServer interface {
	ListBalances(context.Context, *AccountRequest) (*ListBalancesResponse, error)
	ListStatuses(context.Context, *AccountRequest) (*ListStatusesResponse, error)
	ListPerformance(context.Context, *AccountRequest) (*ListPerformanceResponse, error)
}

// UnimplementedHealthServer can be embedded to have forward compatible implementations.
type UnimplementedHealthServer struct {
}

func (*UnimplementedHealthServer) ListBalances(ctx context.Context, req *AccountRequest) (*ListBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBalances not implemented")
}
func (*UnimplementedHealthServer) ListStatuses(ctx context.Context, req *AccountRequest) (*ListStatusesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStatuses not implemented")
}
func (*UnimplementedHealthServer) ListPerformance(ctx context.Context, req *AccountRequest) (*ListPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPerformance not implemented")
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_ListBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ListBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Health/ListBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ListBalances(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_ListStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ListStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Health/ListStatuses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ListStatuses(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_ListPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ListPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Health/ListPerformance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ListPerformance(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ethereum.validator.accounts.v2.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBalances",
			Handler:    _Health_ListBalances_Handler,
		},
		{
			MethodName: "ListStatuses",
			Handler:    _Health_ListStatuses_Handler,
		},
		{
			MethodName: "ListPerformance",
			Handler:    _Health_ListPerformance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/validator/accounts/v2/web_api.proto",
}

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Signup(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Signup(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/ethereum.validator.accounts.v2.Auth/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Login(context.Context, *AuthRequest) (*AuthResponse, error)
	Signup(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Login(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) Signup(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.validator.accounts.v2.Auth/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Signup(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ethereum.validator.accounts.v2.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _Auth_Signup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/validator/accounts/v2/web_api.proto",
}
